title: Public Service Week 2022
description: Description
url: https://www.publicserviceweek.gov.sg
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
resources_name: news
favicon: /images/PSW_Logo.png
google-analytics: UA-40876833-17
permalink: none
baseurl: ""
defaults:
  - scope:
      path: ""
    values:
      layout: page
staging: https://psd-psw-staging.netlify.app
prod: https://psd-psw-prod.netlify.app
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
colors:
  primary-color: "#f153b4"
  secondary-color: "#255cf3"
  media-colors:
    - title: media-color-one
      color: "#f9e41c"
    - title: media-color-two
      color: "#9b9b9b"
    - title: media-color-three
      color: "#ffffff"
    - title: media-color-four
      color: "#4a4a4a"
    - title: media-color-five
      color: "#9b9b9b"
is_government: true
